version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.3-apache-node-browsers
    - image: circleci/mariadb:latest
      environment:
      - MYSQL_ROOT_HOST=%
    working_directory: ~/wordpress-circleci-behat
    steps:
    - restore_cache:
        keys:
          - source-v1-{{ .Branch }}-{{ .Revision }}
          - source-v1-{{ .Branch }}-
    - checkout
    - save_cache:
        key: source-v1-{{ .Branch }}-{{ .Revision }}
        paths:
          - .git
    - run:
        name: Host
        command: |
          sudo cp ~/wordpress-circleci-behat/.circleci/.blog.conf /etc/apache2/sites-available/blog.conf
          sudo a2ensite blog
          sudo service apache2 start
          echo 127.0.0.1 wordpress-circleci-behat.localhost | sudo tee -a /etc/hosts
          cat /etc/hosts
          curl wordpress-circleci-behat.localhost
    - run:
        name: Tools
        command: |
          sudo apt-get -qq update && sudo apt-get -qqy upgrade
          sudo apt-get -yqq install libpng-dev mariadb-client nano
          sudo docker-php-ext-install gd mbstring mysqli pdo pdo_mysql
          sudo service apache2 restart
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.lock" }}
    - run:
        name: Composer
        command: |
          composer global require hirak/prestissimo
          composer install -n --prefer-dist
          echo 'export PATH=$HOME/wordpress-circleci-behat/bin:$PATH' >> $BASH_ENV
          source /home/circleci/.bashrc
    - save_cache:
        paths:
        - ./vendor
        key: v1-dependencies-{{ checksum "composer.lock" }}
    - run:
        name: Install WordPress
        command: |
          cd web
          # Default CircleCI DB name and user:
          wp config create --dbname=circle_test --dbuser=root --dbpass="" --dbhost=127.0.0.1
          # Same as Drush the following command will return sh: 1: -t: not found
          # when it was unable to send mail. @see https://github.com/drush-ops/drush/issues/2338
          wp core install --url=wordpress-circleci-behat.localhost --title="WordPress CircleCI Behat" --admin_user=admin --admin_password=admin --admin_email=admin@wordpress-circleci-behat.localhost
    - run:
        name: Tests
        command: |
          cd tests
          mkdir -p ~/wordpress-circleci-behat/test-results
          behat --config behat.yml --no-snippets -f pretty -o std -f junit -o ~/wordpress-circleci-behat/test-results/junit.xml
    - store_test_results:
        path: test-results
  deploy:
    machine:
      enabled: true
    working_directory: ~/wordpress-circleci-behat
    steps:
    - restore_cache:
        keys:
        - source-v1-{{ .Branch }}-{{ .Revision }}
        - source-v1-{{ .Branch }}-
    - checkout
    - save_cache:
        key: source-v1-{{ .Branch }}-{{ .Revision }}
        paths:
        - .git
#    - run:
#        name: Fix ssh Could not resolve hostname
#        command: |
#          ssh-keyscan "${LIVE_IP}" >> ~/.ssh/known_hosts
#          ssh-keyscan "${DEV_IP}" >> ~/.ssh/known_hosts
#    - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint
#        fingerprints:
#          - "ab:cd:ef:gh:ij:kl:mn:op:qr:st:uv:wx:yz:12:34:56"
#    - run:
#        name: Deploy master
#        command: if [ "${CIRCLE_BRANCH}" == "master" ]; then ssh -p "${LIVE_PORT}" "${LIVE_USER}"@"${LIVE_IP}" "cd /var/www/wordpress-circleci-behat/scripts/deployment && . deploy.sh ${CIRCLE_SHA1}"; else echo "Skipped"; fi
#    - run:
#        name: Deploy dev
#        command: if [ "${CIRCLE_BRANCH}" == "develop" ]; then ssh -p "${DEV_PORT}" "${DEV_USER}"@"${DEV_IP}" "cd /var/www/wordpress-circleci-behat/scripts/deployment && . deploy.sh ${CIRCLE_SHA1}"; else echo "Skipped"; fi
    - run: echo "${CIRCLE_BRANCH}"; echo "${CIRCLE_SHA1}";
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build:
        filters:
          branches:
            only:
            - develop
            - master
    - deploy:
        requires:
        - build
        filters:
          branches:
            only:
            - develop
            - master
